# -*- coding: utf-8 -*-
"""BD_Móveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nVF97diGF2FzuyNTRQIJM7RMJ1g-XENs
"""

# Criar o “banco local” (equivalente a SQLite)

import sqlite3, time, json, random, string, pathlib
from datetime import datetime

DB_PATH = "local_store.db"      # ↔ arquivo .db dentro do app
conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

cur.execute("""
CREATE TABLE IF NOT EXISTS expense (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    title     TEXT        NOT NULL,
    amount    REAL        NOT NULL,
    ts        INTEGER     NOT NULL,
    synced    INTEGER     NOT NULL DEFAULT 0
)
""")
conn.commit()

# Inserir registros “offline”

def add_expense(title, amt):
    cur.execute(
        "INSERT INTO expense(title, amount, ts, synced) VALUES (?, ?, ?, 0)",
        (title, amt, int(time.time()))
    )
    conn.commit()

add_expense("Café aeroporto",   14.50)
add_expense("Táxi hotel",       85.00)
add_expense("Almoço reunião",  129.90)

#Listar tudo que ainda não foi sincronizado

import pandas as pd

df_unsynced = pd.read_sql_query(
    "SELECT id, title, amount, datetime(ts, 'unixepoch') AS ts \
     FROM expense WHERE synced = 0",
    conn
)
df_unsynced

# Simular o WorkManager: gerar PATCH incremental

def build_patch(rows):
    # Converte linhas SQL → dicionário → JSON
    payload = [
        {"id": r["id"], "title": r["title"],
         "amount": r["amount"], "ts": r["ts"]}
        for _, r in rows.iterrows()
    ]
    return json.dumps(payload, indent=2)

patch_json = build_patch(df_unsynced)
print(patch_json)

# “Servidor respondeu 200 OK” → marcar registros como sincronizados

ids = tuple(df_unsynced["id"].tolist())
cur.execute(f"UPDATE expense SET synced = 1 WHERE id IN {ids}")
conn.commit()

# Conferir que não há nada pendente

pd.read_sql_query("SELECT * FROM expense WHERE synced = 0", conn)