# -*- coding: utf-8 -*-
"""Estudo_Caso_BD_Varejista.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4rRqEXemIUl8b7qdSe7nHWZ-Phi3R49
"""

# -----------------------------------------------------------
#  BOOT: cria banco em memória e injeta a versão 1 do esquema
# -----------------------------------------------------------
import sqlite3, json
import pandas as pd

conn = sqlite3.connect(':memory:')
cur  = conn.cursor()

# --- Versão do esquema -------------------------------------
cur.execute('PRAGMA user_version = 1')

cur.executescript("""
CREATE TABLE category (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT    NOT NULL
);
CREATE TABLE item (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  name        TEXT    NOT NULL,
  category_id INTEGER NOT NULL REFERENCES category(id),
  price       REAL    NOT NULL,
  tags_json   TEXT,
  photo_path  TEXT
);
""")

# Seed de categorias e itens de inventário
cur.execute("INSERT INTO category(name) VALUES ('Bebidas'), ('Mercearia')")
cur.execute("""INSERT INTO item(name, category_id, price, tags_json, photo_path)
               VALUES (?,?,?,?,?)""",
            ('Café Torrado', 1, 19.90,
             json.dumps({"origem": "Minas", "tipo": "Arábica"}),
             'photos/cafe.jpg'))
cur.execute("""INSERT INTO item(name, category_id, price, tags_json, photo_path)
               VALUES (?,?,?,?,?)""",
            ('Biscoito Integral', 2, 7.50,
             json.dumps({"semGluten": False, "vegano": True}),
             'photos/biscoito.jpg'))
conn.commit()

# ---------------------------------------------
#  AUDITORIA: inspeção de esquema e amostras v1
# ---------------------------------------------
schema_v1  = pd.read_sql_query("PRAGMA table_info(item)", conn)
sample_v1  = pd.read_sql_query("SELECT id, name, price, tags_json FROM item", conn)

display(schema_v1)   # estrutura da tabela item (v1)
display(sample_v1)   # amostra de registros

# ------------------------------------------------------------
#  MIGRAÇÃO ATÔMICA: barcode (v2) + externalização de fotos (v3)
# ------------------------------------------------------------
cur.executescript("""
BEGIN;                                   -- garante atomicidade
/* v2 -------------------------------------------------------- */
ALTER TABLE item ADD COLUMN barcode TEXT;
PRAGMA user_version = 2;

/* v3 -------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS item_photo (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  item_id    INTEGER NOT NULL REFERENCES item(id),
  photo_path TEXT    NOT NULL
);
INSERT INTO item_photo(item_id, photo_path)
  SELECT id, photo_path FROM item;

/* Nota: SQLite não permite DROP COLUMN direto;        *
 * em produção usar técnica de tabela sombra + rename. */
PRAGMA user_version = 3;
COMMIT;
""")

# ----------------------------------------------------
#  AUDITORIA FINAL: conferência de esquema e dados v3
# ----------------------------------------------------
schema_v3 = pd.read_sql_query("PRAGMA table_info(item)", conn)
photos_v3 = pd.read_sql_query("SELECT * FROM item_photo", conn)

display(schema_v3)   # tabela item agora com 'barcode'
display(photos_v3)   # fotos migradas para item_photo