# -*- coding: utf-8 -*-
"""Feira_Rural.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxxQL37Yv-8t3PqZy2Q7XMwUm7-E61al
"""

# =========================================================
# CÉLULA 1 — UTILITÁRIOS CRIPTO DIDÁTICOS (SEM DEPENDÊNCIAS)
# =========================================================
import os, secrets, time, json, base64, hmac, hashlib
from typing import Tuple

# === PBKDF2 (Password-Based Key Derivation Function 2) ===
def pbkdf2(password: bytes, salt: bytes, length: int = 32, iters: int = 200_000) -> bytes:
    return hashlib.pbkdf2_hmac('sha256', password, salt, iters, dklen=length)

# === HKDF (HMAC-based Key Derivation Function) {Extract, Expand} ===
def hkdf_extract(salt: bytes, ikm: bytes) -> bytes:
    return hmac.new(salt, ikm, hashlib.sha256).digest()

def hkdf_expand(prk: bytes, info: bytes, length: int) -> bytes:
    t = b''; okm = b''; counter = 1
    while len(okm) < length:
        t = hmac.new(prk, t + info + bytes([counter]), hashlib.sha256).digest()
        okm += t; counter += 1
    return okm[:length]

# === AEAD DIDÁTICO (NÃO USE EM PRODUÇÃO): XOR + HMAC-SHA256 ===
# - 'seal' produz (nonce, ciphertext, tag)
# - 'open' valida tag e retorna plaintext
# - Em produção use AES-GCM/ChaCha20-Poly1305 (biblioteca de verdade).
def aead_seal_aula(key: bytes, aad: bytes, plaintext: bytes) -> Tuple[bytes, bytes, bytes]:
    nonce = secrets.token_bytes(12)
    prk   = hkdf_extract(nonce, key)
    ks    = hkdf_expand(prk, b'keystream', len(plaintext))
    ct    = bytes([p ^ k for p, k in zip(plaintext, ks)])
    tag   = hmac.new(key, aad + nonce + ct, hashlib.sha256).digest()
    return nonce, ct, tag

def aead_open_aula(key: bytes, aad: bytes, nonce: bytes, ciphertext: bytes, tag: bytes) -> bytes:
    calc = hmac.new(key, aad + nonce + ciphertext, hashlib.sha256).digest()
    if not hmac.compare_digest(calc, tag):
        raise ValueError("TAG inválida — possível adulteração (integridade violada)")
    prk   = hkdf_extract(nonce, key)
    ks    = hkdf_expand(prk, b'keystream', len(ciphertext))
    return bytes([c ^ k for c, k in zip(ciphertext, ks)])

def b64(x: bytes) -> str:  # helper bonitinho
    return base64.urlsafe_b64encode(x).decode().rstrip("=")

print("Crypto didático pronto. Para produção: AES-GCM/SQLCipher.")

# ============================================================================
# CÉLULA 2 — KMS (Key Management Service) SIMULADO: ROTATE & REVOKE
# - KEK (Key Encryption Key): chave-mestre (seria HSM/KMS em produção)
# - DEK (Data Encryption Key): chave que cifra dados; é "wrappeada" pela KEK
# ============================================================================
from datetime import datetime

AUDIT_LOG = []  # auditoria de eventos de chave

class KMS:
    def __init__(self):
        self.keks = {}     # kid -> KEK bytes
        self.active_kid = None
        self.revoked = set()

    def new_kek(self) -> str:
        kid = f"KID-{secrets.token_hex(4)}"
        self.keks[kid] = secrets.token_bytes(32)  # 256 bits
        self.active_kid = kid
        AUDIT_LOG.append((datetime.utcnow().isoformat(), "NEW_KEK", kid))
        return kid

    def rotate_kek(self) -> str:
        return self.new_kek()

    def revoke_kek(self, kid: str):
        self.revoked.add(kid)
        AUDIT_LOG.append((datetime.utcnow().isoformat(), "REVOKE_KEK", kid))

    # "Wrap" DEK com KEK (didático: HMAC como envelope + XOR)
    def wrap_dek(self, dek: bytes, kid: str = None) -> dict:
        kid = kid or self.active_kid
        assert kid in self.keks and kid not in self.revoked
        kek = self.keks[kid]
        salt = secrets.token_bytes(16)
        # derive "wrapping key" com HKDF
        wk = hkdf_expand(hkdf_extract(salt, kek), b'wrap', len(dek))
        enc = bytes([a ^ b for a, b in zip(dek, wk)])
        tag = hmac.new(kek, salt + enc, hashlib.sha256).digest()
        AUDIT_LOG.append((datetime.utcnow().isoformat(), "WRAP_DEK", kid))
        return {"kid": kid, "salt": b64(salt), "enc": b64(enc), "tag": b64(tag)}

    def unwrap_dek(self, wrapped: dict) -> bytes:
        kid = wrapped["kid"]
        if kid in self.revoked: raise ValueError("KEK revogada — acesso negado")
        kek  = self.keks[kid]
        salt = base64.urlsafe_b64decode(wrapped["salt"] + "==")
        enc  = base64.urlsafe_b64decode(wrapped["enc"] + "==")
        tag  = base64.urlsafe_b64decode(wrapped["tag"] + "==")
        calc = hmac.new(kek, salt + enc, hashlib.sha256).digest()
        if not hmac.compare_digest(calc, tag):
            raise ValueError("Envelope DEK adulterado")
        wk = hkdf_expand(hkdf_extract(salt, kek), b'wrap', len(enc))
        dek = bytes([a ^ b for a, b in zip(enc, wk)])
        return dek

KMS_SIM = KMS()
kid0 = KMS_SIM.new_kek()
DEK  = secrets.token_bytes(32)
WRAPPED = KMS_SIM.wrap_dek(DEK)
print("KID ativo:", kid0, "| DEK wrappeada (base64):", WRAPPED["enc"][:12], "…")

# Demonstra rotação e rewrap
kid1 = KMS_SIM.rotate_kek()
DEK_rewrapped = KMS_SIM.wrap_dek(KMS_SIM.unwrap_dek(WRAPPED), kid=kid1)
KMS_SIM.revoke_kek(kid0)   # antiga fora de jogo

print("KID novo:", kid1, "| REVOGADA:", kid0 in KMS_SIM.revoked)
print("Eventos de auditoria:", len(AUDIT_LOG))

# =============================================================================
# CÉLULA 3 — SQLITE COM CRIPTO NA APLICAÇÃO (DEMO)
# - Cifra colunas sensíveis com AEAD didático (substitua por SQLCipher em prod.)
# - Mascara CPF/GPS nos logs (log hygiene)
# =============================================================================
import sqlite3, re
conn = sqlite3.connect(":memory:")
cur  = conn.cursor()
cur.executescript("""
DROP TABLE IF EXISTS customer;
CREATE TABLE customer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  cpf_ct BLOB NOT NULL,     -- CPF cifrado
  gps_ct BLOB NOT NULL,     -- GPS cifrado
  meta_aad TEXT NOT NULL    -- AAD (Associated Data) claro p/ vincular
);
""")

# Helpers de cifragem de coluna
def encrypt_field(dek: bytes, aad: bytes, value: str) -> bytes:
    n, ct, tag = aead_seal_aula(dek, aad, value.encode())
    return b"|".join([n, ct, tag])

def decrypt_field(dek: bytes, aad: bytes, blob: bytes) -> str:
    n, ct, tag = blob.split(b"|", 2)
    pt = aead_open_aula(dek, aad, n, ct, tag)
    return pt.decode()

DEK_live = KMS_SIM.unwrap_dek(DEK_rewrapped)

# Insert seguro
aad = b"tenant=acme;table=customer;v1"
rows = [
    ("Ana Silva",  "123.456.789-00", "-23.5505,-46.6333"),
    ("Bruno Reis", "987.654.321-99", "-22.9035,-43.2096"),
]
for name, cpf, gps in rows:
    cur.execute(
        "INSERT INTO customer(name, cpf_ct, gps_ct, meta_aad) VALUES (?,?,?,?)",
        (name, encrypt_field(DEK_live, aad, cpf), encrypt_field(DEK_live, aad, gps), aad.decode())
    )
conn.commit()

# Logging hygiene — máscara de CPF e GPS
CPF_RE = re.compile(r'(\d{3}\.\d{3}\.\d{3}-)\d{2}')
GPS_RE = re.compile(r'(-?\d{1,3}\.\d{4,}),(-?\d{1,3}\.\d{4,})')
def mask_log(s: str) -> str:
    s = CPF_RE.sub(r'\1**', s)
    s = GPS_RE.sub(r'\1,**', s)
    return s

# Consulta e demonstração (sem vazar PII em logs)
for rid, name, cpf_ct, gps_ct, aad_txt in cur.execute("SELECT * FROM customer"):
    cpf = decrypt_field(DEK_live, aad, cpf_ct)
    gps = decrypt_field(DEK_live, aad, gps_ct)
    log_line = f"[OK] id={rid} name={name} cpf={cpf} gps={gps}"
    print(mask_log(log_line))  # mostra mascarado

# =============================================================================
# CÉLULA 4 — JWT (JSON Web Token) COM ABAC (Attribute-Based Access Control)
# - Assinatura HS256 (HMAC-SHA256) e 'kid' para rotação
# - Atributos (attrs) e papéis (roles), expiração (exp)
# =============================================================================
import time

def b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode().rstrip("=")

def b64url_decode(data: str) -> bytes:
    return base64.urlsafe_b64decode(data + "==")

# Chaves de assinatura por 'kid' (simulando keystore do auth)
AUTH_KEYS = {"jwt-k1": secrets.token_bytes(32)}
ACTIVE_KID = "jwt-k1"

def jwt_sign(payload: dict) -> str:
    header = {"alg":"HS256","typ":"JWT","kid": ACTIVE_KID}
    h = b64url(json.dumps(header, separators=(",",":")).encode())
    p = b64url(json.dumps(payload, separators=(",",":")).encode())
    mac = hmac.new(AUTH_KEYS[ACTIVE_KID], f"{h}.{p}".encode(), hashlib.sha256).digest()
    return f"{h}.{p}.{b64url(mac)}"

def jwt_verify(token: str) -> dict:
    h_b64, p_b64, s_b64 = token.split(".")
    header = json.loads(b64url_decode(h_b64))
    key = AUTH_KEYS[header["kid"]]
    calc = hmac.new(key, f"{h_b64}.{p_b64}".encode(), hashlib.sha256).digest()
    if not hmac.compare_digest(calc, b64url_decode(s_b64)):
        raise ValueError("Assinatura inválida")
    payload = json.loads(b64url_decode(p_b64))
    if payload.get("exp") and time.time() > payload["exp"]:
        raise ValueError("Token expirado")
    return payload

# Emite token com papéis/atributos
payload = {
    "sub":"user-123",
    "roles":["seller"],
    "attrs":{"limit_offline":500, "market":"rural"},
    "exp": int(time.time()) + 900
}
tok = jwt_sign(payload)
print("JWT:", tok[:60], "…")

# Valida
print("Claims:", jwt_verify(tok))

# Rotação de chave de assinatura
AUTH_KEYS["jwt-k2"] = secrets.token_bytes(32)
ACTIVE_KID = "jwt-k2"
tok2 = jwt_sign(payload)
print("JWT (kid novo):", tok2[:60], "…")

# =============================================================================
# CÉLULA 5 — CERTIFICATE PINNING (SIMULADO)
# - Compara hash (SHA-256) do SPKI (Subject Public Key Info) a pins embutidos
# - Mantém pin de backup para rotação anual
# =============================================================================
def spki_hash(pubkey_der: bytes) -> str:
    return base64.b64encode(hashlib.sha256(pubkey_der).digest()).decode()

PINS = {
    "primary": spki_hash(b"server_pubkey_der_v1"),
    "backup":  spki_hash(b"server_pubkey_der_v2")  # reserva
}

def check_pins(server_pubkey_der: bytes) -> bool:
    h = spki_hash(server_pubkey_der)
    return h in (PINS["primary"], PINS["backup"])

print("Pin OK? (v1):", check_pins(b"server_pubkey_der_v1"))
print("Pin OK? (inválido):", check_pins(b"pubkey_de_terceiro"))

# =============================================================================
# CÉLULA 6 — STATIC ANALYSIS (segredos) + LINT HTTP + LOG RETENTION
# - Regras simples para CI/CD (Continuous Integration/Continuous Delivery)
# =============================================================================
import re, zipfile, io
SAMPLE_CODE = """
const API = "http://api.exemplo.com"; // NÃO PODE HTTP!
# AWS_SECRET_ACCESS_KEY=AKIAZZZZZZZZZZZZZZ
token = "ghp_1234567890abcdefghijklmnopqrstuv"  # GitHub Personal Access Token
"""

FIND_HTTP = re.compile(r'http://')
FIND_AWS  = re.compile(r'AKIA[0-9A-Z]{16}')
FIND_GH   = re.compile(r'ghp_[0-9a-zA-Z]{36}')

issues = []
if FIND_HTTP.search(SAMPLE_CODE): issues.append("Uso de HTTP (não seguro) detectado")
if FIND_AWS.search(SAMPLE_CODE):  issues.append("Possível AWS Access Key detectada")
if FIND_GH.search(SAMPLE_CODE):   issues.append("Possível GitHub token detectado")

print("Issues encontradas:", issues or "Nenhuma (PASS)")

# Log hygiene: compressão e retenção
LOGS = [
    ("2025-07-10","INFO","User login ok"),
    ("2025-08-01","WARN","Excesso de tentativas"),
    ("2025-08-10","INFO","Sync completo 120KB")
]
def prune_logs(days_keep=30, today="2025-08-10"):
    from datetime import datetime, timedelta
    dt_today = datetime.strptime(today, "%Y-%m-%d")
    kept = []
    for d, lvl, msg in LOGS:
        if dt_today - datetime.strptime(d,"%Y-%m-%d") <= timedelta(days=days_keep):
            kept.append((d,lvl,msg))
    return kept

kept = prune_logs(30)
buf = io.BytesIO()
with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as z:
    for i,(d,l,m) in enumerate(kept,1):
        z.writestr(f"log_{i}_{d}.txt", f"{d} {l} {m}\n")
print("Logs mantidos (30d):", len(kept), "| ZIP bytes:", len(buf.getvalue()))

# =============================================================================
# CÉLULA 7 — WIPE REMOTO (REVOGAÇÃO): DECRIPTAÇÃO PASSA A FALHAR
# =============================================================================
# 1) Tenta decriptar normalmente
rec = cur.execute("SELECT id, cpf_ct FROM customer LIMIT 1").fetchone()
try:
    _ = decrypt_field(DEK_live, aad, rec[1])
    print("Antes do wipe: decriptação OK")
except Exception as e:
    print("Erro inesperado:", e)

# 2) Revoga KID ativo no KMS e invalida DEK (simulação de wipe)
KMS_SIM.revoke_kek(kid1)
try:
    # esta DEK "live" deixaria de ser renovada; exemplo didático: zere-a
    DEK_live = b"\x00"*32
    _ = decrypt_field(DEK_live, aad, rec[1])
    print("Após wipe: (não era para chegar aqui)")
except Exception as e:
    print("Após wipe:", str(e))